const { createFixture } = require('./lib/fixture.cjs');
const { _electron } = require('./lib/playwright.cjs');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const root = path.resolve(__dirname, '../..');
  const directory = createFixture(path.join(root, 'work/ux-flow-'));
  const folder = path.join(directory, 'product');
  fs.mkdirSync(folder);
  const { Workroom } = await import('../../src/core/service.mjs');
  const room = new Workroom(path.join(directory, 'workroom.sqlite'));
  room.store.create('runtime-settings', { paused: true, modelId: null });
  room.close();
  const env = { ...process.env, WORKROOM_DATA_DIR: directory, WORKROOM_HEADLESS: '1', WORKROOM_SEMANTIC_SEARCH: '0', WORKROOM_NODE: process.execPath };
  delete env.ELECTRON_RUN_AS_NODE;
  const app = await _electron.launch({ executablePath: require('electron'), args: [root], env });
  try {
    const page = await app.firstWindow();
    page.setDefaultTimeout(12000);
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    await page.locator('[data-action="nav:new-product"]').first().waitFor();
    assert.equal(await page.locator('.product-tabs').count(), 0);
    const call = (method, args) => page.evaluate(async ({ method, args }) => {
      const result = await window.workroom.call(method, args);
      if (!result.ok) throw new Error(result.error);
      return result.value;
    }, { method, args });
    const product = await call('createProduct', { name: 'UX fixture', folder, goal: 'Preserve input' });
    const portfolio = await call('createPortfolio', { target: 'UX target' });
    await call('addRecord', { productId: product.id, title: 'Known record', content: 'Reusable knowledge', scope: 'Fixture only', source: 'UX test' });
    const settle = () => page.waitForFunction(async () => !(await import('./state.js')).ui.busy);
    const click = async (action) => { await page.locator(`[data-action="${action}"]`).first().click(); await settle(); };
    await click('refresh');
    await click('open-portfolio');
    const ai = page.locator(`[data-action="portfolio-edit:${portfolio.id}"]`);
    assert.equal(await ai.isDisabled(), true);
    assert.match(await page.locator('.readiness-list').innerText(), /AI 계정|사용할 모델/);
    assert.match(await page.locator('.readiness-list').innerText(), /강조점/);
    await click(`portfolio-auto:${portfolio.id}`);
    assert.match(await page.locator('.portfolio-agent-panel').innerText(), /준비 필요/);
    assert.equal((await call('snapshot')).portfolioEdits.length, 0);
    await click(`portfolio-account:${portfolio.id}`);
    assert.match(await page.locator('.connection-return').innerText(), /UX target/);
    await click('portfolio-return');
    assert.match(await page.locator('.targetbar').innerText(), /UX target/);
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(760, 600));
    await page.emulateMedia({ colorScheme: 'dark' });
    const bounds = await page.locator('[data-action="edit-portfolio"]').boundingBox();
    assert.ok(bounds.y >= 0 && bounds.y + bounds.height <= 600, 'direct editing visible at minimum window size');
    await click('edit-portfolio');
    await page.locator('#folio-intro').fill('Unsaved introduction');
    await click('portfolio-section:publish');
    assert.equal(await page.locator('#folio-intro').inputValue(), 'Unsaved introduction');
    await click('discard-draft');
    await click('portfolio-section:sources');
    assert.equal(await page.locator('[data-form="job-source"]').count(), 1);
    assert.equal(await page.locator('[data-form="publication-destination"]').count(), 0);
    await page.locator('[name="description"]').fill('Unsaved job source');
    await click('portfolio-section:publish');
    assert.equal(await page.locator('[name="description"]').inputValue(), 'Unsaved job source');
    await click('discard-form');
    await click('portfolio-section:publish');
    assert.equal(await page.locator('[data-form="job-source"]').count(), 0);
    assert.match(await page.locator('.publication-account-status').innerText(), /저장된 토큰 없음|보호 저장소/);
    await click(`publication-prepare:${portfolio.id}`);
    const visibleError = await page.locator('.message .error').evaluate((el) => {
      const r = el.getBoundingClientRect();
      return r.top >= 0 && r.bottom <= innerHeight;
    });
    assert.equal(visibleError, true, 'publication error remains visible after scrolling to prepare');
    assert.match(await page.locator('.message').innerText(), /공개 대상/);
    const output = path.join(root, 'outputs/ux-remediation');
    fs.mkdirSync(output, { recursive: true });
    await page.screenshot({ path: path.join(output, 'publication-error-dark.png') });
    await click('dismiss-message');
    assert.equal(await page.locator('.message .notice').count(), 0);
    if ((await call('snapshot')).publicationAccount.state === 'missing') {
      await click('nav:publish-account');
      const credentials = page.locator('[data-form="publication-credentials"]');
      const token = 'fixture-token-no-provider-call';
      await credentials.locator('[name="token"]').fill(token);
      await credentials.locator('button[type="submit"]').click();
      await settle();
      const snapshot = await call('snapshot');
      assert.deepEqual(snapshot.publicationAccount, { state: 'stored' });
      assert.equal(JSON.stringify(snapshot).includes(token), false);
      assert.match(await page.locator('.publication-account-status').innerText(), /권한은 아직 확인하지/);
      assert.equal(await credentials.locator('[name="token"]').inputValue(), '');
      await click('publication-disconnect');
      assert.equal((await call('snapshot')).publicationAccount.state, 'missing');
    }
    await click(`product:${product.id}`);
    await click('nav:records');
    await page.locator('#record-query').fill('no-match-unique');
    assert.match(await page.locator('#record-results').innerText(), /검색어와 일치/);
    await click('clear-record-query');
    assert.equal(await page.locator('#record-query').inputValue(), '');
    assert.equal(await page.locator('#record-query').evaluate((el) => el === document.activeElement), true);
    await page.getByRole('heading', { name: 'Known record' }).waitFor();
    await click('nav:ops');
    assert.equal(await page.locator('.work-record-actions [data-action="nav:new-work"]').count(), 1);
    // A stored failure exercises the real renderer without calling a model.
    await page.evaluate(async (productId) => {
      const state = await import('./state.js');
      state.data.tasks.push({ id: 'ux-failed', productId, kind: 'agent', mode: 'investigation', stage: 'investigate', status: 'failed', title: 'Fixture failure', message: 'Model connection failed', outputs: {} });
      state.ui.taskId = 'ux-failed';
      (await import('./controller.js')).render();
    }, product.id);
    assert.match(await page.locator('.task-outcome').innerText(), /중단 원인을 해결/);
    assert.doesNotMatch(await page.locator('.task-outcome').innerText(), /다음: 별도 세션/);
    await click('nav:settings');
    await page.locator('#app-language').selectOption('en');
    await page.waitForFunction(() => document.documentElement.lang === 'en');
    await settle();
    await click('open-portfolio');
    await click('portfolio-section:write');
    assert.doesNotMatch(await page.locator('.portfolio-agent-panel').innerText(), /[가-힣]/);
    await page.screenshot({ path: path.join(output, 'portfolio-ai-english-dark.png') });
    await page.emulateMedia({ colorScheme: 'light' });
    await page.screenshot({ path: path.join(output, 'portfolio-ai-english-light.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.deepEqual(errors, []);
    console.log('UX flow: readiness, target return, dirty guards, visible error, search clearing, failure recovery and English passed');
  } finally { await app.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
